[profiles.prod]
PREFECT_SERVER_ALLOW_EPHEMERAL_MODE = "true"
PREFECT_API_URL = "http://0.0.0.0:4201/api"
PREFECT_LOGGING_LEVEL = "DEBUG"
PREFECT_SERVER_API_PORT = "4201"
PREFECT_API_DATABASE_CONNECTION_URL = "sqlite+aiosqlite:///src/orch/db/db.sqlite"

[profiles.uat]
PREFECT_SERVER_ALLOW_EPHEMERAL_MODE = "true"
PREFECT_API_URL = "http://0.0.0.0:4201/api"
PREFECT_LOGGING_LEVEL = "DEBUG"
PREFECT_SERVER_API_PORT = "4201"
PREFECT_API_DATABASE_CONNECTION_URL = "sqlite+aiosqlite:///src/orch/db/db.sqlite"

[profiles.test]
PREFECT_SERVER_ALLOW_EPHEMERAL_MODE = "true"
PREFECT_API_URL = "http://0.0.0.0:4201/api"
PREFECT_LOGGING_LEVEL = "DEBUG"
PREFECT_SERVER_API_PORT = "4201"
PREFECT_API_DATABASE_CONNECTION_URL = "sqlite+aiosqlite:///src/orch/db/db.sqlite"
